$(function(){ // if document is ready
    $('.btn1').click(function(){
        $(this).removeClass('page');
        $(this).addClass('page-block');
        $('.btn2').removeClass('page-block');
        $('.btn2').addClass('page');
        $('.btn3').removeClass('page-block');
        $('.btn3').addClass('page');
        $('.section1').css('display','block');
        $('.section2').css('display','none');
        $('.section3').css('display','none');
    });
    $('.btn2').click(function(){
        $(this).removeClass('page');
        $(this).addClass('page-block');
        $('.btn1').removeClass('page-block');
        $('.btn1').addClass('page');
        $('.btn3').removeClass('page-block');
        $('.btn3').addClass('page');
        $('.section1').css('display','none');
        $('.section2').css('display','block');
        $('.section3').css('display','none');
    });
    $('.btn3').click(function(){
        $(this).removeClass('page');
        $(this).addClass('page-block');
        $('.btn1').removeClass('page-block');
        $('.btn1').addClass('page');
        $('.btn2').removeClass('page-block');
        $('.btn2').addClass('page');
        $('.section1').css('display','none');
        $('.section2').css('display','none');
        $('.section3').css('display','block');
    });
  });